"""empty message

Revision ID: 93debc148847
Revises: 9bdf0a75729b
Create Date: 2017-11-15 00:26:17.608501

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '93debc148847'
down_revision = '9bdf0a75729b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('avatar', sa.String(length=128), nullable=True))
    op.drop_index('ix_users_email', table_name='users')
    op.drop_column('users', 'email')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('email', sa.VARCHAR(length=64), nullable=True))
    op.create_index('ix_users_email', 'users', ['email'], unique=1)
    op.drop_column('users', 'avatar')
    # ### end Alembic commands ###
